### ISSUE TITLE
The search functionality is broken

### ISSUE THREAD

**Issue by clive-machado** [mohammedtalyb/search-table#1]
**Context:**
Since we’ve pushed the code on the last commit f97ad95c2e852754eae0723b757fa226e365849d the search functionality doesn't work as expected.

**Steps to Recreate:**
1) Search "test4" on page 1.
2) It will load a set of result.
3) Remove the search text "test4"
4) Move to page 7 search "test4" again
5) I do not get any results

**Solution or next step:**
I should receive the same set of search results no matter which page I navigate to.

**Comment by mohammedtalyb** [comment]
issue resolved with commit - 
63acb7d00f7cf240b088cc02d243b0b5673ac0d4
