### ISSUE TITLE
The pagination logic is not correct

### ISSUE THREAD

**Issue by clive-machado** [mohammedtalyb/search-table#2]
**Context:**
Since we’ve pushed the code on the last commit f97ad95c2e852754eae0723b757fa226e365849d the pagination functionality doesn't work as expected.

**Steps to Recreate:**
1) Move to page 7 search "test4"
2) The pagination displays "7/1"

**Solution or next step:**
The pagination should show "1/1" since there are no results found.

**Comment by mohammedtalyb** [comment]
issues has been resolved in the latest commit:
63acb7d00f7cf240b088cc02d243b0b5673ac0d4
