### ISSUE TITLE
Not able to search items from different pages

### ISSUE THREAD

**Issue by clive-machado** [mohammedtalyb/search-table#3]
**Context:**
Since we’ve pushed the code on the last commit f97ad95c2e852754eae0723b757fa226e365849d the search functionality doesn't work as expected.

**Steps to Recreate:**
1) Move to page 7 search "tJJKKJJest"
2) I do not get any results 
3) Move to page 1 search "tJJKKJJest" again
4) I get three results

**Solution or next step:**
I should receive the same set of search results no matter which page I navigate to.

**Comment by mohammedtalyb** [comment]
issues has been resolved in the latest commit:
63acb7d00f7cf240b088cc02d243b0b5673ac0d4
