### ISSUE TITLE
The "Next" page button is displayed on top of table data.

### ISSUE THREAD

**Issue by clive-machado** [mohammedtalyb/search-table#4]
**Context:**
Since we’ve pushed the code on the last commit e91319bac4305c1a63b1a34f9ce3456f57e18410 the page button is displayed on top of table.

**Steps to Recreate:**
1) Load the page.
<img width="1380" alt="Screenshot 2019-05-13 at 11 14 30 AM" src="https://user-images.githubusercontent.com/25608284/57598449-e5945000-7570-11e9-8a6d-ac4f79c1bb84.png">

**Solution or next step:**
The button should not be on top of the table.

**Comment by mohammedtalyb** [comment]
issue resolved with commit - 
ce535f464011f5a9968633ddc8b327620665e293
